-- MySQL Script generated by MySQL Workbench
-- 07/08/15 15:07:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Badge` (
  `badge_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL DEFAULT 'Sem nome',
  `img` VARCHAR(45) NOT NULL DEFAULT 'badge',
  `badge_desc` VARCHAR(250) NOT NULL DEFAULT 'Sem descrição',
  `obtain` TINYINT(1) NOT NULL DEFAULT 1,
  `titulo` VARCHAR(250) NOT NULL DEFAULT 'Sem título',
  `score` INT NULL DEFAULT 0,
  PRIMARY KEY (`badge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `face_id` VARCHAR(25) NOT NULL DEFAULT '457676144377257',
  `nome_min` VARCHAR(45) NOT NULL,
  `nome_full` VARCHAR(250) NOT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `skill` VARCHAR(45) NOT NULL DEFAULT 'Sem skill',
  `race` VARCHAR(45) NOT NULL DEFAULT 'Humana',
  `blood` VARCHAR(45) NOT NULL DEFAULT 'Azul',
  `crest` INT NOT NULL DEFAULT 0,
  `tier` INT NOT NULL,
  PRIMARY KEY (`face_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Member_has_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member_has_` (
  `Member_face_id` VARCHAR(25) NOT NULL,
  `_badge_id` INT NOT NULL,
  PRIMARY KEY (`Member_face_id`, `_badge_id`),
  INDEX `fk_Member_has__1_idx` (`_badge_id` ASC),
  INDEX `fk_Member_has__Member_idx` (`Member_face_id` ASC),
  CONSTRAINT `fk_Member_has__Member`
    FOREIGN KEY (`Member_face_id`)
    REFERENCES `mydb`.`Member` (`face_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has__1`
    FOREIGN KEY (`_badge_id`)
    REFERENCES `mydb`.`Badge` (`badge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
